version: '3.4'

services:
  hpool-chia-miner-pp:
    build: .
    restart: unless-stopped
    volumes:
      - /mnt/storage/pool:/mnt/storage/pool:ro
      - ${PWD}/config.yaml:/hpool/config.yaml:ro
      - /root/clx-chia-multi-setup/log:/hpool/log:rw
    stdin_open: true
    tty: true

volumes:
  log:
